### ISSUE TITLE
update License

### ISSUE THREAD

**Issue by aditpape** [x42/fil4.lv2#10]
have you ever thought about changing license to e.g LGPL2?
Library code as GPL makes is quite impossible to quarantee a legal usage in big commercial projects.
As a consequence it might be strictly forbidden to use any components based on GPL.
The GPL license is a big hurdle which likely restricts some users from using that nice plugin...

**Comment by x42** [comment]
It's not a library, it's a plugin. Loading the plugin at runtime has no effect the license requirements of the host or vice versa (one example: nvidia binary driver and Linux kernel).

The GPL is places no restriction on commercial use. You just cannot use the source-code in closed-source proprietary projects.  

I'm not sure what you mean with "big commercial projects". The resulting audio or any sound processed with the EQ is not subject to the license (just like code compiled with gcc is not subject to gcc's license).

I'm happy with the GPL and I'm also not the only author, so I cannot change the license without accord of all (C) holders. It's unlikely that the license will change.

**Comment by aditpape** [comment]
As per my understanding and currently given policies even the 'runtime linking' is not allowed with GPL code w/o getting 'infected'. That's why LGPL was introduced to explicitly allow dynamic linking. 
But if you do not have the complete ownership of all contributions to the project - as you stated - you might anyway not change the license....
THX

**Comment by x42** [comment]
You don't link the host against the plugin. The plugin is loaded at runtime (and optional).

"A main program that is separate from its plug-ins makes no requirements for the plug-ins." https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins

**Comment by aditpape** [comment]
That's the opposite case - the question is: having proprietary program an link/load a GPL plugin: 
https://www.gnu.org/licenses/gpl-faq.html#NFUseGPLPlugins

"If they form a single combined program then the main program must be released under the GPL or a GPL-compatible free software license"
AND: 
"If the main program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single combined program, which must be treated as an extension of both the main program and the plug-ins."

There seems some room for interpretation, but at least 'loading a plugin' (dlopen) must be considered as dynamic linking and thus above rule is very likely applicable.

Thank you for your answers.

**Comment by x42** [comment]
[dynamic] linking usually means that the program itself won't run if the dependent lib is not available.
dlopen is not linking and also audio plugins don't use  "shared memory to communicate with complex data structures". Plugin APIs are deliberately simple.

Since "complex data structure" is undefined, it is indeed a bit of a gray area, and if you pay a lawyer a significant amount of money s/he may make a case for you. But if dlopen'ing Audio Plugins would require merging the licenses of the host (and all other plugins loaded concurrently) I'm sure the proprietary/commercial world would have had a couple of law-suits already. Also consider: "If the main program uses fork and exec...": the Windows OS comes to mind. A lot of the syscalls are way more complex than audio plugin APIs and some even to use shmem with complex data structures. and more so: Windows10 ships a "Linux subsystem" these days.

JUCE is another example that can produce GPL'ed plugins and it's pretty common in the audio-world.

As for the case at hand, I certainly won't enforce the GPL for audio-plugins that I wrote which are loaded at runtime in a proprietary host, and I'm confident that co-authors won't do either.  The whole point of the GPL is to provide freedom to the user (and not limit it).

PS. For libraries where the interface is more important than the implementation, I prefer the MIT license or -- depending on collaborators -- LGPL.
